[package]
name = "paperclip-proto"
version = "0.1.0"
edition = "2021"
description = "Protobuf definitions for Paperclip"

[dependencies]
prost = "0.13"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
