[package]
name = "paperclip-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
logos.workspace = true
chumsky.workspace = true
bumpalo.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
crc32fast = "1.4"
ariadne = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true

[features]
default = ["pretty-errors"]
pretty-errors = ["ariadne"]

[[bench]]
name = "parser_bench"
harness = false
