[package]
name = "paperclip-sourcemap"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sourcemap = "8.0"
thiserror.workspace = true

[dev-dependencies]
# Add test dependencies if needed
